name:                list-witnesses
version:             0.1.2.0
github:              "mstksg/list-witnesses"
license:             BSD3
author:              "Justin Le"
maintainer:          "justin@jle.im"
copyright:           "(c) Justin Le 2018"
tested-with:         GHC >= 8.4

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Witnesses for working with type-level lists
category:            Dependent Types

description: |
  Collection of assorted inductive witnesses and functions for working with
  type-level lists.

  *   *Data.Type.List.Edit* contains single-item edits of lists, including
      insertion, deletion, and substitution.
  *   *Data.Type.List.Sublist* contains witnesses for prefixes, suffixes, and
      two-way splits of type-level lists.

ghc-options:
- -Wall
- -Wcompat
- -Wredundant-constraints
- -Werror=incomplete-patterns

library:
  source-dirs: src
  dependencies:
  - base >= 4.7 && < 5
  - decidable >= 0.1.5
  - profunctors
  - singletons
  - vinyl
  - microlens
  - functor-products
